apiVersion: v1
kind: Service
metadata:
 name: maven-service
 labels:
   app: maven
spec:
 #type: LoadBalancer
 type: NodePort
 selector:
  component: web
 ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: maven
  name: logs
spec:
 accessModes:
 - ReadWriteOnce
 resources:
   requests:
     storage: 2Gi
 storageClassName: glusterfs-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: maven
 name: maven
spec:
 replicas: 1
 selector:
  matchLabels:
   component: web
 template:
  metadata:
   labels:
    component: web
    app: maven
  spec:
   securityContext:
    runAsUser: 0
   volumes:
    - name: logs
      persistentVolumeClaim:
        claimName: logs
   containers: 
    - name: maven
      image: 35.226.190.199:30503/maven
      ports:
       - containerPort: 8080
      volumeMounts:
       - mountPath: /logs
         name: logs
