apiVersion: v1
kind: Template
labels:
  template: bluegreen-pipeline
metadata:
  name: bluegreen-pipeline
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${LABEL}
    name: blue-${NAME}
  spec:
    to:
      kind: Service
      name: ${NAME}-blue
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${LABEL}
    name: green-${NAME}
  spec:
    to:
      kind: Service
      name: ${NAME}-green
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${LABEL}
    name: ${NAME}
  spec:
    alternateBackends:
    - name: ${NAME}-green
      weight: 0
    to:
      kind: Service
      name: ${NAME}-blue
      weight: 100
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: ${LABEL}
    name: "${NAME}-blue"
  spec:
   accessModes:
   - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
   storageClassName: glusterfs-storage
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    labels:
      app: ${LABEL}
    name: "${NAME}-green"
  spec:
   accessModes:
   - ReadWriteOnce
   resources:
     requests:
       storage: 2Gi
   storageClassName: glusterfs-storage
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${LABEL}
    name: ${NAME}-blue
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${LABEL}
      deploymentconfig: ${NAME}-blue
      name: ${NAME}-blue
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${LABEL}
    name: ${NAME}-blue
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true" #Template instantiation will not complete until this object report ready
  spec:
    strategy:
      type: "Rolling"
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: false
        containerNames:
        - ${NAME}
        from: 
          kind: ImageStreamTag
          name: "${NAME}:blue"
      type: ImageChange
    replicas: 1
    selector:
      app: ${LABEL}
      deploymentconfig: ${NAME}
      name: ${NAME}-blue
    template:
      metadata:
        labels:
          app: ${LABEL}
          deploymentconfig: ${NAME}
          name: ${NAME}-blue
      spec:
        volumes:
        - name: "${NAME}-blue"
          persistentVolumeClaim:
            claimName: "${NAME}-blue"
        containers:
        - image: " "
          name: ${NAME}
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 512Mi
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /logs
              name: "${NAME}-blue"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 360
            timeoutSeconds: 180
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 180
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    labels:
      app: ${LABEL}
    name: ${NAME}-blue
  spec:
    maxReplicas: 10
    minReplicas: 3
    scaleTargetRef:
      apiVersion: v1
      kind: DeploymentConfig
      name: "${NAME}-blue"
    targetCPUUtilizationPercentage: 90
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${LABEL}
    name: ${NAME}-green
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${LABEL}
      deploymentconfig: ${NAME}-green
      name: ${NAME}-green
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${LABEL}
    name: ${NAME}-green
    annotations:
      template.alpha.openshift.io/wait-for-ready: "true" #Template instantiation will not complete until this object report ready
  spec:
    strategy:
      type: "Rolling"
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: false
        containerNames:
        - ${NAME}
        from: 
          kind: ImageStreamTag
          name: "${NAME}:green"
      type: ImageChange
    replicas: 1
    selector:
      app: ${LABEL}
      deploymentconfig: ${NAME}
      name: ${NAME}-green
    template:
      metadata:
        labels:
          app: ${LABEL}
          deploymentconfig: ${NAME}
          name: ${NAME}-green
      spec:
        volumes:
        - name: "${NAME}-green"
          persistentVolumeClaim:
            claimName: "${NAME}-green"
        containers:
        - image: " "
          name: ${NAME}
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 512Mi
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /logs
              name: "${NAME}-green"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 360
            timeoutSeconds: 180
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 180
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    labels:
      app: ${LABEL}
    name: ${NAME}-green
  spec:
    maxReplicas: 10
    minReplicas: 3
    scaleTargetRef:
      apiVersion: v1
      kind: DeploymentConfig
      name: "${NAME}-green"
    targetCPUUtilizationPercentage: 90
parameters:
- description: The name assigned to all of the frontend objects defined in this template.
  displayName: Name
  name: NAME
  required: true
- description: The label assigned to all of the frontend objects defined in this template.
  displayName: App label
  name: LABEL
  required: true
- name: SECRET_ENV
  displayName: Secret environments name
  required: true
